# Generated by Django 2.2.12 on 2020-05-24 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200524_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cost',
            field=models.CharField(default='OBO', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish'), (2, 'Scheduled')], default=1),
        ),
    ]
